---
title: "Tidy data"
author: "Aakriti Gupta"
date: "Oct 1, 2018"
output: html_document
---


##importing files

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(knitr)
options(tibble.print_min = 5)
```

## gather

PULSE data

```{r}
pulse_data = haven::read_sas("public_pulse_data.sas7bdat") %>%
  janitor::clean_names() 
pulse_data
```
 This isnt tidy yet...
 
```{r}
pulse_tidy = pulse_data %>%
  gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m)
```
 
 Illustrate 'separate':
 
```{r}
pulse_tidy %>% 
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = '_') %>% 
select(-bdi_str, -score_str) %>% 
mutate(visit = replace(visit, visit == "bl", "00m")) 
pulse_tidy
```
 
 All together pipeline
```{r}
pulse_df = haven::read_sas("public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>% 
  gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m) %>% 
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = '_') %>% 
select(-bdi_str, -score_str) %>% 
mutate(visit = replace(visit, visit == "bl", "00m")) 
  pulse_df
```
 
